name: Deploy Frontend to AWS

on:
  push:
    branches:
      - development  # Grana

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # AWS region

    - name: Deploy to S3
      run: |
        aws s3 sync ./system-test-matrix/frontend s3://your-s3-bucket-name/  # bucket

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id YOUR_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
